#!/usr/bin/env bash

lxappearance
sleep 1

cp $HOME/.gtkrc-2.0 \
    $HOME/Projects/dots/gtk/.gtkrc-2.0

cp $HOME/.config/gtk-3.0/settings.ini \
    $HOME/Projects/dots/gtk/.config/gtk-3.0/settings.ini

$HOME/Scripts/stowConfigs.sh
