#!/bin/bash
################################################################################
#Author: Frank Camilleri (http://deployfrank.sh)
#TL;DR: a wrapper of the retheme.sh wrapper with default args. For builtin themes.
#Invoke with no args to produce a list of possible themes.
#License: MIT (do w/e you want with this code as long as MIT license copy
#included, and I'm not responsible if this code breaks your stuff)
################################################################################

$HOME/Scripts/retheme.sh --theme $@
