#!/bin/sh

B='{color8}ff'  # blank
C='{color5}22'  # clear ish
D='{color0}ff'  # default
T='{color7}ff'  # text
W='{color1}ff'  # wrong
V='{color2}ff'  # verifying

/usr/bin/i3lock \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 1            \
--blur 5              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
--keylayout 2         \
--veriftext="Thinking..."   \
--wrongtext="ERROR"   \
# --textsize=20 \
# --modsize=10  \
--timefont=ubuntu   \
--datefont=ubuntu   \
# etc
